---
title: Optika Adria | Okulistične specialistične ambulante
description: Sončna očala, Korekcijska očala, Kontaktne leče. Vaš optik na območju države Slovenia. Adria Optika samo najboljše za vaše oči.
url: "https://www.adriaoptika.si"
baseurl: # the subpath of your site, e.g. /blog
timezone: CET
encoding: UTF-8
lang: sl-SI
name: "adriaoptika"
logo: "/img/logo-60x600px.png"
email: adriaplast@adriaplast.si
tel: '+38656776740'

social:
  name: adriaoptika
  links:
    - https://www.facebook.com/Adria-Optika-Portorož-536281293103204/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

feed:
  categories:
    - Orto & Giardino

# Build settings
markdown: kramdown

exclude:
  - ".gitignore"
  - CNAME

sass:
    style: compressed

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  profile: false
